### PR TITLE
Fix e2e names and emails and make validation rules for `Sign{Up,In}Form` match gitea

### LINKED ISSUE #481: e2e generates possibly real email addresses
If we ever accidentally hook up an email server while testing it will try and send a bunch of emails. Most likely outcome is we will get a lot of bounces and get blocked because of it. We might even email some real people by mistake. 

We should use `@example.com` addresses which is made for this purpose, has no MX record and the SMTP port isn't open so will prevent further harm. (https://serverfault.com/a/333552)

### LINKED ISSUE #482: e2e can generate invalid username
image

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
- e2e: use faker `userName` instead of `firstName` and @example emails.
- Make validation rules for `Sign{Up,In}Form` match gitea.
##
Fixes #482 and closes #481

### CODE REVIEW

File: e2e/cypress/support/getFakeUsername.js [hunk 1]
```diff
@@ -2,18 +2,22 @@ import faker from 'faker'
 
 /**
  * `faker.unique` isn't that unique; sometimes it returns a previously used username.
- * @returns {string} unique username
+ * @returns {{username: string, email: string, password: string}}}}}
  */
-export const getFakeUsername = () => {
+export const getFakeUser = () => {
```
Comment (kasbah) [inline e2e/cypress/support/getFakeUsername.js:7]: I think the file should be renamed too.
