### PR TITLE
Handle readme `a` and `img` elements with no URLs

### LINKED ISSUE #437: `8BitmixtapeNEO_ShenzhenReady` processing fails
https://github.com/8BitMixtape/8BitmixtapeNEO_ShenzhenReady

```
Acquired sync lock for  /gitea-data/git/repositories/tester/8bitmixtapeneo_shenzhenready.git
Pulling updates for /gitea-data/git/repositories/tester/8bitmixtapeneo_shenzhenready.git
Released sync lock for  /gitea-data/git/repositories/tester/8bitmixtapeneo_shenzhenready.git
in_progress tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/kitspace-yaml.json
in_progress tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/1-click-BOM.tsv
in_progress tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/bom-info.json
in_progress tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/readme.html
in_progress tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/interactive_bom.json
failed tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/interactive_bom.json No PCB file found
done tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/1-click-BOM.tsv
done tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/bom-info.json
done tester/8bitmixtapeneo_shenzhenready/d8f86818c2ad3206abc9b7a0ed26dfdf672dba10/kitspace-yaml.json
```

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
If an `a` element doesn't have a `href` attribute or an `img` element doesn't have a `src` attribute it would break our readme URL transformer. 
For example https://github.com/8BitMixtape/8BitmixtapeNEO_ShenzhenReady readme is
```
# 8BitmixtapeNEO_ShenzhenReady

summary: <a summary for your project> <- This invalid <a>  tag, probably it's meant as a placeholder
site:https://8bitmixtape.github.io/NeoWiki
```
##
Fixes #437

### CODE REVIEW

File: processor/test/integration/test_readme_processing.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+describe('Readme processing', function () {
+    beforeEach(async function () {
+        await exec(`mkdir -p ${tmpDir}`)
+        await exec(`mkdir -p ${repoDir}`)
+        this.app = createApp(repoDir, { giteaDB: null })
+        this.supertest = supertest(this.app)
+    })
+
+    it("it process remade with invalid <a> tags", async function () {
```
Comment (kasbah) [inline processor/test/integration/test_readme_processing.ts:24]:
```suggestion
    it("processes readme with invalid <a> tags", async function () {
```

File: processor/test/integration/test_readme_processing.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+import { createApp } from '../../src/app.js'
+import { delay } from '../../src/utils.js'
+
+const exec = util.promisify(cp.exec)
+
+const tmpDir = '/data/test/temp/kitspace-processor-test-from-folder'
+const repoDir = path.join(tmpDir, 'repos')
+
+
+describe('Readme processing', function () {
```
Comment (kasbah) [inline processor/test/integration/test_readme_processing.ts:16]:
```suggestion
describe('readme processing', function () {
```

File: processor/test/integration/test_readme_processing.ts [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+import path from 'node:path'
+import supertest from 'supertest'
+import util from 'node:util'
+
+import { createApp } from '../../src/app.js'
+import { delay } from '../../src/utils.js'
+
+const exec = util.promisify(cp.exec)
+
+const tmpDir = '/data/test/temp/kitspace-processor-test-from-folder'
```
Comment (kasbah) [inline processor/test/integration/test_readme_processing.ts:12]:
```suggestion
const tmpDir = '/data/test/temp/kitspace-processor-test-from-folder-readme-processing'
```

**Review by kasbah — CHANGES_REQUESTED** [review]
Some minor things.

The fact that this readme just says "Accepted" on master is really worrying by the way :laughing:  but I think it'll get fixed after we move to s3 properly.
