### PR TITLE
 Use plotted gerbers when `eda` is available

### LINKED ISSUE #455: `open-source-rover-shield` wrong board showcase
https://github.com/nasa-jpl/open-source-rover

|v1|v2|
|---|---|
|image|image|

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
Fixes #455

### CODE REVIEW

**Comment by AbdulrhmnGhanem** [comment]
@kasbah, I am not sure how to test this tough. I want to make sure it generated the right `top.svg`  file, I can't md5 hash it because the file hash changes each time the tests run.

**Comment by kasbah** [comment]
Could use a visual test but I'm not sure if the effort is worth it.

**Comment by AbdulrhmnGhanem** [comment]
>Could use a visual test but I'm not sure if the effort is worth it.

I managed to get a consistent hash of the images in dcfa58fe68346ddee462c68ca611557e10ab1c92.

File: processor/src/tasks/processGerbers/index.ts [hunk 1]
```diff
@@ -69,31 +69,32 @@ export default async function processGerbers(
...
-    // being a number that works for the projects currently on kitspace. it
-    // could cause problems with new projects and should be fixed in
-    // whats-that-gerber
-    // https://github.com/tracespace/tracespace/issues/357
-    if (gerbers.length < 5) {
-      if (plottedGerbers.gerbers.length === 0) {
+    let inputFiles: PlottedGerbers['inputFiles']
+    let gerbers: PlottedGerbers['gerbers']
+
+    if (plottedGerbers.gerbers.length === 0) {
```
Comment (kasbah) [inline processor/src/tasks/processGerbers/index.ts:75]:
```suggestion
    if (kitsyaceYaml.gerbers != null || plottedGerbers.gerbers.length === 0) {
```

I think you are reversing this bug otherwise. It will use the plotted Gerbers even when it has a Gerber folder from kitspace.yaml.

**Comment by kasbah** [comment]
Thanks for merging the auto-format PR but it means you'll have to rebase and auto-format this.

File: processor/src/tasks/processGerbers/index.ts (hunk 1 above)
Comment (AbdulrhmnGhanem) [reply processor/src/tasks/processGerbers/index.ts:75]: Do you know a repo I can use as a test case for this?

Comment (kasbah) [reply processor/src/tasks/processGerbers/index.ts:75]: I'm afraid not and I have also re-written all the tests for the s3 work already. Let's open an issue to add a test case for it.

File: processor/src/tasks/processKicadPCB/index.ts [hunk 2]
```diff
@@ -46,7 +46,13 @@ async function processKicadPCB(
...
       )
 
-    const gerbers = await gerbersPromise
+    // Only plot gerbers if there's no `gerbers` key in kitspace.yaml.
+    let gerbers = []
+    if (kitspaceYaml.gerbers == null) {
+      gerbers = await gerbersPromise
+    }
+
+    // const gerbers = await gerbersPromise
```
Comment (kasbah) [inline processor/src/tasks/processKicadPCB/index.ts:55]: This way it's still plotting the gerbers but not using the result so it's wasted work. (Also, there's some commented out code which should be removed.)
